import './Styles/body.css'
import './Styles/main.css'

function Body() {
  return (
    <div className="cardtailwind" id='crd'>
    	<div className="w-auto m-3 bg-gray-700 rounded-md grid grid-cols-1 divide-y divide-gray-500 " >
			<h1 className="text-center text-3xl p-2">Introduction</h1>
			<p className="p-2">
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
iLorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
			placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
	Lorem ipsum dolor sit amet, consecteturctetur adipiscing elit. Morbi placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
			placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
	Lorem ipsum dolor sit amet, consecteturctetur adipiscing elit. Morbi placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
			placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi placerat ligula lacus, non bibendum ante auctor sit amet. Nam tristique turpis sapien, ut tempor erat luctus ut. Cras tincidunt ipsum eget condimentum facilisis. Ut velit sapien, faucibus in sodales id, ornare vitae lorem. Donec at mauris orci. Nunc condimentum ante at eros venenatis feugiat. Vivamus pretium mauris libero, posuere dictum leo suscipit a. Integer a arcu ut ipsum hendrerit vestibulum nec sed augue. Sed feugiat, arcu quis tincidunt molestie, purus sapien laoreet ligula, non aliquam arcu nibh non purus. Proin vitae libero ut dui tincidunt convallis. Phasellus vitae pretium turpis. Sed ut egestas tellus.
			
			</p>
		</div>
    </div>
  );
}

export default Body;
